### ISSUE TITLE
Update XO to fix failing tests

### ISSUE THREAD

**Issue by binyamin** [sindresorhus/html-tags#10]
Tests are failing. Specifically, XO complains because the code imports JSON files. This is fixed in _v0.25.0_.

While we're on the topic, _v0.27.0_ adds Typescript support, which would allow linting the `*.d.ts` files. It requires Node.js 10, though, and this project currently requires Node.js 8. The highest version which supports non-ESM code is _v0.39.1_.

Which version should we update to, if at all?

**Comment by sindresorhus** [comment]
I don't plan to update any dev tooling until I can move this package to ESM. I have worked around the lint error.
