### ISSUE TITLE
Import Assertions Issues with Node + Typescript + Jest

### ISSUE THREAD

**Issue by JavierScars** [sindresorhus/html-tags#13]
Is someone else having issues with this library using Node + Typescript after updating it to V4?
I cannot find a way to make it work with Jest.

Node: v18.20.4 (I've also tried V20)
Jest: 29.7.0
TypeScript: 5.4.3

P.S: For some reason, it seems to be working when I build/serve the project (I'm using Next) but no when I run the tests.

**Comment by sindresorhus** [comment]
This is a problem with Jest and you should open an issue on the Jest issue tracker instead.

**Comment by JavierScars** [comment]
You were right

In any case, if someone else is having issues running Jest having this lib in the project the solution is adding this library to the `transformIgnorePatterns` exceptions array inside the jest config (jest.config.js).

It should look something like this 
`transformIgnorePatterns: ['/node_modules/(?!html-tags)']`
